### ISSUE TITLE
Can't see http Status group & response time(duration) on graphite..

### ISSUE THREAD

**Issue by cosmir17** [RustedBones/akka-http-metrics#18] opened 2019-08-08 12:04 UTC
Hi :)

I used the following two dependencies
```
    "fr.davit"               %% "akka-http-metrics-core" % "0.5.0",
    "fr.davit"               %% "akka-http-metrics-datadog" % "0.5.0",
```

I have the following setting
```
  val registry = DatadogRegistry(JimiStatsDClient.apply)
    val settings = HttpMetricsSettings.default.withIncludeStatusDimension(true).withIncludePathDimension(true)

    Http().bindAndHandle(routes.recordMetrics(registry, settings), httpInterface, httpPort)
```
I have the following metrics folder in my graphite.
![Screenshot 2019-08-08 at 13 00 59](https://user-images.githubusercontent.com/2845708/62701598-a2fdda80-b9dc-11e9-9b97-41c48b8b085b.png)

However, I am not seeing,
http Status counts & response time(duration).

Please let me know if I have missed something.

Thank you,
Sean

**Comment by RustedBones** [comment] 2019-08-08 13:14
Hi @cosmir17 . Thanks posting the issue.

I've run this tests for the statsd client as bellow:
```scala
val settings = HttpMetricsSettings.default.withIncludePathDimension(true).withIncludeStatusDimension(true)
  val registry = DatadogRegistry(new NonBlockingStatsDClient("test", "localhost", 8081))

  val route: Route = (get & path("message"))(complete("test"))

  Http().bindAndHandle(route.recordMetrics(registry, settings), "localhost", 8080)
```

I'm listening UDP packets on port `8081` with `netcat -ulC 8081`  and after calling `curl localhost:8080/message` I have:
```
test.akka.http.connections_count:1|c
test.akka.http.connections_active:1|c
test.akka.http.requests_active:1|c
test.akka.http.requests_count:1|c
test.akka.http.requests_bytes:0|d
test.akka.http.requests_active:-1|c
test.akka.http.responses_count:1|c|#path:/proto,status:2xx
test.akka.http.responses_duration:502|d|#path:/proto,status:2xx
test.akka.http.responses_bytes:4|d|#path:/proto,status:2xx
test.akka.http.connections_active:-1|c
```

This seems complywith the [datagram format](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/) definition.

Seems on your screenshots that you are missing all the responses metrics.

What is the implementation of your `StatsDClient`? I didn't manage to find `JimiStatsDClient` on GitHub. Maybe the underlying implementation creates some problem with the library. I'd like to run the same test with it.

**Comment by cosmir17** [comment] 2019-08-08 13:18
I am using NonBlockingStatsDClient from theDatadog library.
"com.datadoghq" % "java-dogstatsd-client" % "2.8"

I should have read the documentation more thoroughly.
I tried the following.

lazy val routes: Route = {
      pathLabeled(Neutral, "topLevel") {
        firstRoutes ~ secondRoutes ~ thirdRoutes ~ fourthRoutes
      }
  }

My request are now rejected. Do you know why? Neutral should match any request.

**Comment by RustedBones** [comment] 2019-08-08 13:28
If your inner routes also contain paths directives it will fail.

`pathLabeled` works as `path` and rejects requests if there is some unmatched segments.
you should probably try with `pathPrefixLabeled`

**Comment by RustedBones** [comment] 2019-08-08 13:38
If your inner routes also contain paths directives it will fail.

pathLabeled works as path and rejects requests if there is some unmatched segments.
you should probably try with pathPrefixLabeled

Edit: `Neutral` doesn't consume anything and extracts nothing meaning in this case that `pathLabeled(Neutral, "topLevel")`  or `path(Neutral)` will only match `/`

**Comment by cosmir17** [comment] 2019-08-08 13:40
I am really thankful for your advice.
I tried 'pathPrefixLabeled' and it didn't work.

I tried a different api in your library. The following seems working.

```
lazy val routes: Route = {
     rawPathPrefixLabeled(Neutral, "topLevel") {
        firstRoutes ~ secondRoutes ~ thirdRoutes ~ fourthRoutes
      }
  }
```
Once I see metrics in graphite. I shall close this ticket :) Thank you for helping me.

**Comment by RustedBones** [comment] 2019-08-08 13:48
Indeed, anytime `path` or `pathPrefix` is used, a new segment is expected. Using `Neutral` would lead to match a double slash path.

However in your example, your `topLevel` label will not be present in the metrics since there is nothing to be replaced in `Neutral` (it does not match any character).
The goal of the labelled path is to replace what is matched by the given label to generate the metrics path.

**Comment by cosmir17** [comment] 2019-08-08 14:06
The Akka documentation describes Neutral as 'A matcher that always matches'.
However, as you said, it doesn't show on graphite. I don't know the meaning of 'replace' in this context.

What would be your suggestion in order for me to get all the http response status codes for every request?

**Comment by cosmir17** [comment] 2019-08-08 14:43
@RustedBones Hi, I debugged on my IDE, 
With 'Neutral', it's always hitting the following line as shown on the screenshot,
```
response.addHeader(new SegmentLabelHeader(from, to, "/" + label))
```
However, it doesn't send metrics to Graphite. (same result)

![Screenshot 2019-08-08 at 15 41 43](https://user-images.githubusercontent.com/2845708/62712593-0b57b680-b9f3-11e9-82e6-46ac2d9823c9.png)

**Comment by cosmir17** [comment] 2019-08-08 15:31
@RustedBones, I made changes per API end points.
![Screenshot 2019-08-08 at 16 23 08](https://user-images.githubusercontent.com/2845708/62716224-b66b6e80-b9f9-11e9-9f96-47374d421a27.png)

I still don't have 'request, active requests.. etc' metrics. However, I am not getting any response related ones. (http status codes, duration etc).

**Comment by RustedBones** [comment] 2019-08-08 16:05
Enabling the path dimension will create labels for all paths in your server. Eg:
```scala
pathPrefix("my" / "experience") {
  path("listen") {
    complete()
  } ~ path("practice") {
    complete()
  }
}
```

will create metrics with labels `path=/my/experience/listen` & `path=/my/experience/practice`.

No need of the`pathLabeled` directive.Those are meant to be used when part of your path contains a variable (in case of dynamic path matching like `Segment`,  `IntNumber`, ...).

You can then probably sum your metrics starting with `/my/experience` in graphite if you are not interested in the full path.

Concerning the absence of response metrics, could you help be debug by checking the udp datagrams with netcat instead of running your statsd server and look for the presence of response metrics ?

**Comment by cosmir17** [comment] 2019-08-08 16:10
@RustedBones the debug screenshot was taken when I ran my test cases. The graphite result was not due to the execution of the test cases. There are clients making 'status' requests.

I shall get the udp datagrams asap.

**Comment by cosmir17** [comment] 2019-08-08 16:48
@RustedBones I can't netcat. It's test env and I don't have the application on the server. I don't have previelige install the application.

**Nonehteles, my Graphite should have received Response metrics for "status" endpoint.
What can be a cause of the issue?**

I use the following two dependencies (I deleted the core one, the result is same):
```
    "fr.davit"               %% "akka-http-metrics-datadog" % rustedBonesMetrics,
    "com.datadoghq"          %  "java-dogstatsd-client"  % "2.8",
```

**Comment by RustedBones** [comment] 2019-08-09 12:01
@cosmir17 I ran the tests against a the [graphite-statsd](https://hub.docker.com/r/graphiteapp/graphite-statsd/) instead of `netcat` and I observed the following in the logs:
```
9 Aug 11:35:59 - DEBUG: Bad line: 1,c,#path in msg "akka.http.responses_count:1|c|#path:/test,status:2xx"
9 Aug 11:35:59 - DEBUG: Bad line: /test,status in msg "akka.http.responses_count:1|c|#path:/test,status:2xx"
9 Aug 11:35:59 - DEBUG: Bad line: 2xx in msg "akka.http.responses_count:1|c|#path:/test,status:2xx"
9 Aug 11:35:59 - DEBUG: Bad line: 508,d,#path in msg "akka.http.responses_duration:508|d|#path:/test,status:2xx"
9 Aug 11:35:59 - DEBUG: Bad line: /test,status in msg "akka.http.responses_duration:508|d|#path:/test,status:2xx"
9 Aug 11:35:59 - DEBUG: Bad line: 2xx in msg "akka.http.responses_duration:508|d|#path:/test,status:2xx"
9 Aug 11:35:59 - DEBUG: Bad line: 4,d,#path in msg "akka.http.responses_bytes:4|d|#path:/test,status:2xx"
9 Aug 11:35:59 - DEBUG: Bad line: /test,status in msg "akka.http.responses_bytes:4|d|#path:/test,status:2xx"
9 Aug 11:35:59 - DEBUG: Bad line: 2xx in msg "akka.http.responses_bytes:4|d|#path:/test,status:2xx"
```

Looking at the original [statsd](https://github.com/statsd/statsd#usage) definition, there is no mention of tags or sample rate support:

> \<metricname\>:\<value\>|\<type\>

Graphite statsd server seems to stick to this definition and fails parsing datagram containing those extensions.

Looking at the [graphite documentation](https://graphite.readthedocs.io/en/latest/tags.html#graphite-tag-support), seems that tag support is only supported via carbon.

**Comment by RustedBones** [comment] 2019-08-09 12:35
Since the root cause of the problem is found, I'll close the issue.

I've opened a new one to enable carbon support for graphite (#20)

**Closed by RustedBones** 2019-08-09 12:35 UTC
Labels: question
