### ISSUE TITLE
when 4xx request the metrics shows as different end point !!

### ISSUE THREAD

**Issue by sreeniall** [RustedBones/akka-http-metrics#41] opened 2020-03-09 14:58 UTC

**Comment by RustedBones** [comment] 2020-03-09 22:15
I think this is a duplicate of #19. Can you confirm ?

**Comment by sreeniall** [comment] 2020-03-10 07:52
Yes , This is same Michel.. , I hope you fixed ..Thank you

**Comment by RustedBones** [comment] 2020-03-11 19:34
closing as duplicate

**Closed by RustedBones** 2020-03-11 19:34 UTC
